//this file wrapps up all the files in the project
import './globals.css'
import { Montserrat } from "@next/font/google"
import Link from 'next/link'

const montserrat = Montserrat({ //specific font from @next/font library
  weight:["400","900"],
  subsets: ["latin"]
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <div className='flex my-10'>
          <Link className='m-auto' href="/">Back to home page</Link>
        </div>
        {children}
      </body>
    </html>
  )
}
